[versions]
agp = "8.6.1"
activityCompose = "1.9.0"
androidMapsUtils = "2.4.0"
androidPdfViewer = "2.8.2"
appcompat = "1.7.0"
balloon = "1.6.3"
biometric = "1.1.0"
calendarview = "1.0.4"
cardview = "1.0.0"
checkout = "1.6.39"
securePrefernce = "1.0.0"
circleimageview = "3.1.0"
circleindicator = "2.1.6"
coilCompose = "2.0.0-rc01"
commonsCodec = "1.15"
constraintlayout = "2.1.4"
constraintlayoutCompose = "1.1.0-alpha13"
converterGson = "2.9.0"
converterScalars = "2.6.1"
coreKtx = "1.13.1"
coreVersion = "3.5.0"
datastorePreferences = "1.1.1"
desugar_jdk_libs = "2.0.4"
easypermissionsKtx = "1.0.0"
espressoCore = "3.6.1"
firebaseConfig = "22.1.0"
firebaseCrashlytics = "19.4.1"
firebaseCrashlyticsBuildtools = "3.0.3"
firebaseDatabaseKtx = "21.0.0"
firebaseFirestoreKtx = "25.0.0"
firebaseMessaging = "24.1.0"
firebaseStorageKtx = "21.0.0"
foundationLayout = "1.6.8"
fragmentKtx = "1.8.1"
glide = "4.16.0"
gson = "2.10.1"
hiltAndroid = "2.47"
intentsdk = "5.1.1"
junit = "1.2.1"
junitVersion = "4.13.2"
koinAndroid = "3.5.3"
koinAndroidExt = "3.0.1"
koinAndroidxCompose = "3.0.1"
kotlinStdlibJdk8 = "1.9.21"
kotlinxCoroutinesAndroid = "1.7.3"
legacySupportV4 = "1.0.0"
lifecycleLivedataKtx = "2.8.3"
loggingInterceptor = "4.9.3"
lottie = "6.3.0"
material = "1.12.0"
materialCalendarViewVersion = "1.9.0-rc03"
materialVersion = "1.6.8"
mpandroidchart = "v3.1.0"
navigationUiKtx = "2.7.7"
okhttp = "4.12.0"
pagingRuntimeKtx = "3.3.0"
playServicesMaps = "19.0.0"
playServicesLocation = "21.3.0"
preferenceKtx = "1.2.1"
printerlibrary = "1.0.18"
qrgenerator = "1.0.1"
recyclerview = "1.4.0"
retrofit = "2.9.0"
roomKtx = "2.5.0"
runtimeLivedata = "1.6.8"
runtimeVersion = "1.1.1"
sdpAndroid = "1.1.0"
seatbookview = "1.0.3"
shimmer = "0.5.0"
slf4jApi = "1.7.30"
sspAndroid = "1.1.0"
startupRuntime = "1.1.1"
timber = "5.0.1"
toastcompat = "1.1.0"
ui = "1.6.8"
whynotimagecarousel = "2.0.2"
zxingAndroidEmbedded = "4.3.0"
kotlinPlugin = "1.8.10"
composeBom = "2024.06.00"
firebaseCrashlatics = "3.0.2"
firebaseAnalytics= "22.0.2"
googleServices = "4.4.2"

mapsplatformSecrets = "2.0.1"
devtoolsKSP = "1.8.10-1.0.9"
sentryAndroid = "5.10.0"
updateCore = "2.1.0"
assetCore = "2.2.2"
featureCore = "2.1.0"
flexbox = "3.0.0"
activity = "1.9.0"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
android-maps-utils = { module = "com.google.maps.android:android-maps-utils", version.ref = "androidMapsUtils" }
android-pdf-viewer = { module = "com.github.barteksc:android-pdf-viewer", version.ref = "androidPdfViewer" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "foundationLayout" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleLivedataKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
androidx-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "ui" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
applandeo-material-calendar-view = { module = "com.applandeo:material-calendar-view", version.ref = "materialCalendarViewVersion" }
balloon = { module = "com.github.skydoves:balloon", version.ref = "balloon" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
calendarview = { module = "com.github.kizitonwose:CalendarView", version.ref = "calendarview" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
checkout = { module = "com.razorpay:checkout", version.ref = "checkout" }
securePreference = { module = "androidx.security:security-crypto", version.ref = "securePrefernce" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
circleindicator = { module = "me.relex:circleindicator", version.ref = "circleindicator" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
common = { module = "android.arch.core:common", version.ref = "runtimeVersion" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterScalars" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlinStdlibJdk8" }
update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "updateCore" }
asset-delivery-ktx = { module = "com.google.android.play:asset-delivery-ktx", version.ref = "assetCore" }
feature-delivery-ktx = { module = "com.google.android.play:feature-delivery-ktx", version.ref = "featureCore" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-runtime = { module = "android.arch.core:runtime", version.ref = "runtimeVersion" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
easypermissions-ktx = { module = "com.vmadalin:easypermissions-ktx", version.ref = "easypermissionsKtx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
firebase-config = { module = "com.google.firebase:firebase-config", version.ref = "firebaseConfig" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalytics"  }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-crashlytics-buildtools = { module = "com.google.firebase:firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
firebase-perf = { module = "com.google.firebase:firebase-perf", version.ref = "firebaseStorageKtx" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx", version.ref = "firebaseStorageKtx" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
intentsdk = { module = "phonepe.intentsdk.android.release:IntentSDK", version.ref = "intentsdk" }
junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
junit-junit = { module = "junit:junit", version.ref = "junitVersion" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-android-ext = { module = "io.insert-koin:koin-android-ext", version.ref = "koinAndroidExt" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesAndroid" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleLivedataKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationUiKtx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
qrgenerator = { module = "com.github.androidmads:QRGenerator", version.ref = "qrgenerator" }
printerlibrary = { module = "com.sunmi:printerlibrary", version.ref = "printerlibrary" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
seatbookview = { module = "com.github.JahidHasanCO:SeatBookView", version.ref = "seatbookview" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
toastcompat = { module = "me.drakeet.support:toastcompat", version.ref = "toastcompat" }
whynotimagecarousel = { module = "org.imaginativeworld.whynotimagecarousel:whynotimagecarousel", version.ref = "whynotimagecarousel" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
zxing-core = { module = "com.google.zxing:core", version.ref = "coreVersion" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

[plugins]
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
android-library = { id = "com.android.library", version.ref = "agp" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlatics" }
google-services-gms = { id = "com.google.gms.google-services", version.ref = "googleServices" }
mapsplatform-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "mapsplatformSecrets" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtoolsKSP" }
sentry-android = { id = "io.sentry.android.gradle", version.ref = "sentryAndroid" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinPlugin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlinPlugin" }
